[dev]
  command = "npm run dev"

[build]
  publish = "dist"
  functions = "functions"

[[redirects]]
  from = "/here"
  to = "https://weather.ls.hereapi.com/weather/1.0/report.json?apiKey=HEREAPI&product=observation&oneobservation=true&metric=false&name=Seattle"
  status = 200
  force = true
  headers = {X-From = "Netlify"}